// Mycelium Framework — VibeSpace LLC — The network provides.
//
// expo-supabase contract appendix.
//
// Empirically derived from the 2026-05-07 LiveGrid cultivation run, which
// produced 24 contract-drift type errors. Every section below is the version
// that, when applied as a frozen contract, blocks the failure mode it targets.
//
// Sections A, B, D, F are stack-universal: they apply to ANY expo-supabase
// organism. Sections C and E are split — universal rules + baseline rows are
// here; organism-specific entity types, enum members, and the route map are
// generated by the planner from the brief and appended at plant time.

import type { ContractAppendix } from "./index.js";

const PREAMBLE = `This appendix is the frozen contract surface for any organism on the expo-supabase stack. It exists to block the contract-drift class of failure: missing runtime deps, component prop drift, inline style-array typing failures, icon-name drift, and duplicate barrel exports.

> The mycelium planner MUST copy every subsection below verbatim into the matching section of NUTRIENTS.md. No paraphrasing. No placeholders. No \`#TODO\`. Sections C and E are partly verbatim (universal rules) and partly planner-generated (organism-specific rows the planner appends from the agent decomposition). Leaves reading NUTRIENTS treat these as frozen contracts — amendments only via FRUIT_READY contract-amendment line, never silent edits.`;

const DEPENDENCY_MANIFEST = `Single source of truth for runtime deps. Default owner is \`app-shell\`. A biome that needs a package not on this list MUST emit \`+dep:<pkg>@<ver> reason:<one-line>\` on its FRUIT_READY line, or the orchestrator rejects the harvest. No biome may add a runtime import for a package not on this list. Versions are pinned to Expo SDK 54 (validated end-to-end through bundle in 2026-05-08 LiveGrid run-3).

**Runtime:**
- expo@~54.0.0 — owner: app-shell
- react@19.1.0 — owner: app-shell
- react-native@0.81.5 — owner: app-shell
- @react-navigation/native@^6.1.9 — owner: app-shell
- @react-navigation/native-stack@^6.9.17 — owner: app-shell
- @react-navigation/bottom-tabs@^6.5.11 — owner: app-shell
- @supabase/supabase-js@^2.39.0 — owner: app-shell
- @react-native-async-storage/async-storage@2.2.0 — owner: app-shell
- expo-auth-session@~7.0.11 — owner: auth
- expo-web-browser@~15.0.11 — owner: auth
- expo-secure-store@~15.0.8 — owner: auth
- expo-image-picker@~17.0.11 — owner: app-shell
- expo-linking@~8.0.12 — owner: auth
- expo-splash-screen@~31.0.13 — owner: app-shell
- expo-status-bar@~3.0.9 — owner: app-shell
- @expo/vector-icons@^15.0.2 — owner: design-system
- react-native-reanimated@~4.1.1 — owner: app-shell
- react-native-worklets@~0.5.1 — owner: app-shell — REQUIRED transitive of reanimated@4
- react-native-gesture-handler@~2.28.0 — owner: app-shell
- react-native-safe-area-context@~5.6.2 — owner: app-shell
- react-native-screens@~4.16.0 — owner: app-shell
- react-native-svg@~15.12.1 — owner: design-system — REQUIRED for BrandIcon SVG rendering
- react-native-url-polyfill@^2.0.0 — owner: app-shell — REQUIRED for @supabase/supabase-js on RN

**Dev:**
- @types/react@~19.1.0 — owner: app-shell — MUST match react@19.1 peer range
- typescript@^5.3.0 — owner: app-shell

**Install workflow** (MUST be documented in CLAUDE.md or README):
React Native peer-dep ranges drift faster than npm's resolver tolerates. ALWAYS install with \`npm install --legacy-peer-deps\`. If a leaf needs to add a dep at install time, use \`npx expo install <pkg>\` (which picks the SDK-aligned version) — NEVER raw \`npm install <pkg>\`.

Routing is locked to \`@react-navigation/*\` (NOT \`expo-router\`). The \`package.json\` "main" field MUST be \`index.js\` (the React Navigation entry), not \`expo-router/entry\`.`;

const PRIMITIVE_PROPS = `Full TS interfaces for every shared primitive in \`src/components/primitives/\`. Frozen: leaves cannot add, remove, or rename props. The design-system biome MUST ship exactly these signatures. If a consumer biome needs a prop not listed, it amends the contract via FRUIT_READY contract-amendment line — never inlines a workaround.

\`\`\`ts
import type React from 'react';
import type { ViewStyle, TextStyle } from 'react-native';
import type { Ionicons } from '@expo/vector-icons';

export type IoniconsName = React.ComponentProps<typeof Ionicons>['name'];

export interface ButtonProps {
  children: React.ReactNode;
  onPress: () => void;
  size?: 'sm' | 'md' | 'lg';
  variant?: 'primary' | 'secondary' | 'ghost' | 'destructive';
  disabled?: boolean;
  loading?: boolean;
  fullWidth?: boolean;
  leftIcon?: IoniconsName;
  rightIcon?: IoniconsName;
  style?: ViewStyle;
  textStyle?: TextStyle;
  accessibilityLabel?: string;
}

export interface InputProps {
  value: string;
  onChangeText: (v: string) => void;
  placeholder?: string;
  label?: string;
  helperText?: string;
  error?: string;
  disabled?: boolean;
  secureTextEntry?: boolean;
  multiline?: boolean;
  numberOfLines?: number;
  leftIcon?: IoniconsName;
  rightIcon?: IoniconsName;
  style?: ViewStyle;       // outer container
  inputStyle?: TextStyle;  // text element
}

export interface CardProps {
  children: React.ReactNode;
  variant?: 'default' | 'elevated' | 'outlined' | 'flat';
  padding?: 'none' | 'sm' | 'md' | 'lg';
  onPress?: () => void;
  style?: ViewStyle;
  accessibilityLabel?: string;
}

export interface AvatarProps {
  source?: { uri: string } | number;  // remote URL or require()
  name?: string;                       // for initials fallback
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  shape?: 'circle' | 'square';
  showOnlineStatus?: boolean;
  isOnline?: boolean;
  style?: ViewStyle;
}

export interface TagProps {
  children: React.ReactNode;
  variant?: 'default' | 'primary' | 'success' | 'warning' | 'danger';
  size?: 'sm' | 'md';
  onPress?: () => void;
  onRemove?: () => void;
  style?: ViewStyle;
}

export interface BrandIconProps {
  /** Locked to the brand glyphs the organism actually uses. The planner narrows
   *  this union to the organism's specific brand list at plant time, but every
   *  expo-supabase organism MUST define BrandIcon as a distinct component
   *  separate from <Ionicons>. */
  name: string;
  size?: number;
  color?: string;
  style?: ViewStyle;
}

export interface ScreenProps {
  children: React.ReactNode;
  scrollable?: boolean;
  padded?: boolean;
  edges?: Array<'top' | 'bottom' | 'left' | 'right'>;
  style?: ViewStyle;
  contentContainerStyle?: ViewStyle;
}

export interface SpinnerProps {
  size?: 'sm' | 'md' | 'lg';
  color?: string;
  style?: ViewStyle;
}

export interface DividerProps {
  vertical?: boolean;
  color?: string;
  thickness?: number;
  spacing?: number;
  style?: ViewStyle;
}

export interface SpacerProps {
  size?: number;          // spacing scale key (e.g. 1=4, 2=8, 4=16)
  horizontal?: boolean;
  flex?: boolean | number;
  style?: ViewStyle;
}

// Typography — every text node in the app uses one of these. No raw <Text>.
export type TextColor =
  | 'primary' | 'secondary' | 'tertiary' | 'muted' | 'inverse'
  | 'link' | 'success' | 'warning' | 'error';

export interface HeadingProps {
  children: React.ReactNode;
  level?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5';
  color?: TextColor;
  align?: 'left' | 'center' | 'right';
  style?: TextStyle;
}

export interface BodyProps {
  children: React.ReactNode;
  size?: 'large' | 'default' | 'small';
  color?: TextColor;
  align?: 'left' | 'center' | 'right';
  bold?: boolean;
  style?: TextStyle;
}

export interface CaptionProps {
  children: React.ReactNode;
  color?: TextColor;
  align?: 'left' | 'center' | 'right';
  medium?: boolean;
  style?: TextStyle;
}

export interface LabelProps {
  children: React.ReactNode;
  color?: TextColor;
  align?: 'left' | 'center' | 'right';
  uppercase?: boolean;
  style?: TextStyle;
}
\`\`\``;

const BASELINE_OWNERSHIP = `Every shared symbol has exactly ONE owner biome. No biome exports a symbol another biome has claimed. If a biome needs a symbol it does not own, it imports — never re-declares.

The rows below are stack-universal — they exist in every expo-supabase organism because the primitives, theme, and Supabase client are stack-baseline. The planner MUST append organism-specific rows below this baseline (entity types, biome components, hooks, contexts) derived from the brief.

| Symbol | Owner biome | File path |
|---|---|---|
| \`supabase\` (client) | app-shell | \`src/lib/supabase.ts\` |
| \`RootStackParamList\` | app-shell | \`src/navigation/types.ts\` |
| \`Screen\`, \`ScreenProps\` | app-shell | \`src/components/Screen.tsx\` |
| \`AuthSession\` | auth | \`src/contexts/AuthContext.tsx\` |
| \`AuthContext\` (interface) | auth | \`src/contexts/AuthContext.tsx\` |
| \`useAuth\` | auth | \`src/hooks/useAuth.ts\` |
| \`IoniconsName\` | design-system | \`src/components/primitives/Button.tsx\` |
| \`Button\`, \`ButtonProps\` | design-system | \`src/components/primitives/Button.tsx\` |
| \`Input\`, \`InputProps\` | design-system | \`src/components/primitives/Input.tsx\` |
| \`Card\`, \`CardProps\` | design-system | \`src/components/primitives/Card.tsx\` |
| \`Avatar\`, \`AvatarProps\` | design-system | \`src/components/primitives/Avatar.tsx\` |
| \`Tag\`, \`TagProps\` | design-system | \`src/components/primitives/Tag.tsx\` |
| \`BrandIcon\`, \`BrandIconProps\` | design-system | \`src/components/primitives/BrandIcon.tsx\` |
| \`Spinner\`, \`SpinnerProps\` | design-system | \`src/components/primitives/Spinner.tsx\` |
| \`Divider\`, \`DividerProps\` | design-system | \`src/components/primitives/Divider.tsx\` |
| \`Spacer\`, \`SpacerProps\` | design-system | \`src/components/primitives/Spacer.tsx\` |
| \`Heading\`, \`Body\`, \`Caption\`, \`Label\` (+ Props) | design-system | \`src/components/primitives/Typography.tsx\` |
| \`TextColor\` | design-system | \`src/components/primitives/Typography.tsx\` |
| \`theme\`, \`useThemeTokens\` | design-system | \`src/theme/index.ts\` |
| \`tokens\`, \`colors\`, \`spacing\`, \`radii\`, \`shadows\`, \`typography\` | design-system | \`src/theme/tokens.ts\` |

Cardinal rule: a primitive's \`Props\` type is owned by design-system. NEVER re-declared in the consumer's barrel.`;

const BARREL_OWNERSHIP = `A biome may not write to a barrel it does not own. To surface a new export, a biome lands the file under its owned tree and the barrel owner picks it up the next wave (or via FRUIT_READY contract-amendment line). Each barrel re-exports ONLY from its allowed scope.

| Barrel path | Owner biome | Allowed exports |
|---|---|---|
| \`src/index.ts\` | app-shell | App entry + root navigator only. NO type re-exports (prevents duplicate-export collisions). |
| \`src/components/index.ts\` | design-system | Re-exports from \`./primitives\` only. NO biome-level components (those import directly from their own paths). |
| \`src/components/primitives/index.ts\` | design-system | All primitives + their Props types. MUST NOT re-export entity types or domain enums. |
| \`src/types/index.ts\` | schema-core | All entity interfaces + domain enum types. Sole source of truth for organism-specific enums. |
| \`src/screens/index.ts\` | app-shell | Re-exports from each biome's screen tree. Other biomes write screen files; only app-shell touches this barrel. |
| \`src/navigation/index.ts\` | app-shell | Navigators + \`RootStackParamList\`. |
| \`src/hooks/index.ts\` | app-shell | Re-exports each hook from its owning biome's path (e.g. \`export { useAuth } from './useAuth';\`). New hooks: file lands in owner tree, app-shell adds re-export. |
| \`src/lib/index.ts\` | app-shell | Re-exports \`supabase\` (app-shell) + any other lib utilities, each from its owning biome. |
| \`src/contexts/index.ts\` | app-shell | Re-exports each context provider from its owning biome's path. |
| \`src/theme/index.ts\` | design-system | \`theme\`, \`useThemeTokens\`, all token constants. NOT re-exported through \`src/index.ts\`. |

Cardinal rule: a symbol appears in EXACTLY ONE barrel. The duplicate-export TS2308 error class comes from this rule being violated; treating it as frozen blocks the regression.`;

const ALLOWLISTED_IDENTIFIERS = `**Ionicons names.** All icon name literals in JSX MUST be type-checked against the Ionicons name union:

\`\`\`ts
import type { Ionicons } from '@expo/vector-icons';
export type IoniconsName = React.ComponentProps<typeof Ionicons>['name'];
\`\`\`

Any prop typed as \`IoniconsName\` will cause \`tsc --noEmit\` to reject typos and non-existent names (e.g. \`"logo-spotify"\` is not a valid Ionicons name). NEVER pass an arbitrary string to \`<Ionicons name=... />\`. NEVER cast (\`as IoniconsName\`, \`as any\`).

**Brand icons.** Brand glyphs (Spotify, Google, Facebook, Apple, etc.) are NOT in Ionicons and must NEVER be referenced via \`<Ionicons name="logo-spotify" />\` or similar. They MUST go through:

\`\`\`tsx
<BrandIcon name="..." />
\`\`\`

\`BrandIcon\` is owned by design-system. The planner narrows its \`name\` prop union to the specific brand glyphs the organism uses (appended below by the planner). Any biome that needs a brand glyph not in the locked union amends the contract — never inlines an SVG or string.

**Domain enums.** Every domain enum (categories, statuses, roles, etc.) is owned by schema-core, defined in \`src/types/index.ts\`, and consumed via import. The planner appends the full enum list below from the brief.

**Route names.** Owned by app-shell. The full route map is exposed as a typed \`RootStackParamList\` so navigation calls type-check at the literal level. The planner appends the full route map below from the brief's screen inventory. Every \`navigation.navigate(...)\`, \`Stack.Screen name=...\`, and \`useRoute()\` call resolves against this map. Adding a route requires app-shell amending \`RootStackParamList\`. Biomes do NOT define their own route name strings inline.`;

const STYLE_SYSTEM_RULES = `1. **NEVER hardcode hex colors in component code.** All colors come from \`theme.colors.<key>\`. Rationale: tints appear at multiple opacities in tokens; raw hex defeats the token system and prevents future light-mode work.

   \`\`\`ts
   // GOOD
   const tokens = useThemeTokens();
   <View style={{ backgroundColor: tokens.colors.primary }} />
   // BAD
   <View style={{ backgroundColor: '#7C5CFF' }} />
   \`\`\`

2. **Inline conditional styles use object spread, not array unions.** TypeScript rejects \`(false | TextStyle)[]\` against \`ViewStyle | TextStyle\`, which is the failure-mode that produces inline-style-array errors.

   \`\`\`ts
   // GOOD
   const s: ViewStyle = {
     flex: 1,
     ...(active && { backgroundColor: tokens.colors.primary }),
   };
   <View style={s} />

   // GOOD (multiple conditions, single object)
   <View
     style={{
       padding: 16,
       ...(disabled && { opacity: 0.5 }),
       ...(error && { borderColor: tokens.colors.error }),
     }}
   />

   // BAD — TS2322 / TS2769 territory
   <Text style={[styles.text, cond && { color: '#fff' }]} />
   \`\`\`

3. **\`ViewStyle\` and \`TextStyle\` are mutually exclusive at the leaf node.** A component prop typed \`style?: ViewStyle\` MUST NOT receive text-only properties (\`color\`, \`fontSize\`, \`fontWeight\`, \`lineHeight\`, \`letterSpacing\`, \`textAlign\`, \`textTransform\`). Text props go into the corresponding \`inputStyle\` / \`textStyle\` / \`style\` on a Typography primitive. Rationale: TS will flag the cross-mix only inconsistently — the contract makes intent unambiguous.

4. **Every screen wraps its top-level content in \`<Screen>\` (app-shell).** \`Screen\` owns safe-area insets, scroll behavior, status-bar wiring, and screen-padding tokens. Leaves DO NOT import \`SafeAreaView\`, \`ScrollView\` (at the screen level), or \`StatusBar\` directly. Modals have their own wrapper but follow the same rule.

   \`\`\`tsx
   // GOOD
   export function MyScreen() {
     return (
       <Screen scrollable padded>
         <Heading level="h1">Hello</Heading>
       </Screen>
     );
   }
   \`\`\`

5. **Theme imports use the \`@/theme\` path alias** defined in \`tsconfig.json\` (\`"paths": { "@/*": ["src/*"] }\`). No biome creates a parallel theme file or local color/spacing constants. There is exactly one \`tokens.ts\`, owned by design-system.

   \`\`\`ts
   // GOOD
   import { useThemeTokens } from '@/theme';
   // BAD
   const PRIMARY = '#7C5CFF'; // do not redefine
   \`\`\`

6. **Raw \`<Text>\` from \`react-native\` is forbidden in screen and biome code.** Use \`Heading\` / \`Body\` / \`Caption\` / \`Label\` from primitives. Rationale: raw \`<Text>\` skips the typography token scale and produces inconsistent line-heights across the app. Exception: design-system's own Typography primitives import \`Text as RNText\` internally — that is the ONLY allowed usage.

7. **External service clients (Supabase, Stripe, etc.) MUST default-stub when env vars are missing.** Throwing on missing config blocks the boot path during demo cultivation when no real backend is wired. The pattern:

   \`\`\`ts
   // GOOD — supabase.ts
   const supabaseUrl =
     process.env.EXPO_PUBLIC_SUPABASE_URL ?? 'https://placeholder.supabase.co';
   const supabaseAnonKey =
     process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY ?? 'placeholder-anon-key';

   if (!process.env.EXPO_PUBLIC_SUPABASE_URL) {
     console.warn('[supabase] Missing env vars; using placeholders. Network calls will fail.');
   }

   export const supabase = createClient(supabaseUrl, supabaseAnonKey, { ... });

   // BAD — throws before any UI renders
   if (!supabaseUrl) throw new Error('supabaseUrl is required.');
   \`\`\`

   Rationale: a demo cultivation must boot to a visible UI even without backend credentials, so reviewers can validate the visual + navigation surface. Real failures surface at API-call time, not import time.

8. **\`app.json\` MUST NOT reference assets that don't exist.** No \`icon\`, \`splash.image\`, \`android.adaptiveIcon.foregroundImage\`, or \`web.favicon\` paths unless the corresponding files are produced by the design-system biome. If those assets aren't generated, omit the fields entirely (Expo falls back to its own defaults). Likewise, NEVER write a placeholder \`extra.eas.projectId: "your-project-id"\` — Expo CLI tries to log into EAS when it sees a placeholder ID and a missing asset, blocking the dev server. Either real EAS project ID or omit the \`extra.eas\` block.

9. **\`RootNavigator\` (app-shell) MUST import the real screen component for every route.** Stubbing routes with \`PlaceholderScreen\` that returns \`null\` produces a black-screen demo. The Screen Ownership Matrix in §G lists the canonical import for every route; \`RootNavigator.tsx\` MUST follow it. If a route's owning biome hasn't shipped its screen yet, the placeholder MUST render a visible component (e.g., centered route name on theme background) — never \`return null\`.

10. **Import path conventions for common packages** (avoid the wrong-subpath leaf bug):

    \`\`\`ts
    // Supabase URL polyfill — the side-effect import that registers globalThis.URL
    import 'react-native-url-polyfill/auto';            // GOOD
    import 'react-native-url-polyfill/dist/index';      // BAD (wrong subpath)

    // Reanimated — used as a Babel plugin (in babel.config.js), NOT imported in app code
    // (worklets is a transitive of reanimated@4 — install but don't import)

    // Async storage — single named import
    import AsyncStorage from '@react-native-async-storage/async-storage';
    \`\`\``;

const SCREEN_OWNERSHIP_MATRIX = `Every route in §E's \`RootStackParamList\` maps to exactly one screen file owned by exactly one biome. \`RootNavigator.tsx\` (owned by app-shell) imports each screen at the listed path. THIS IS LOAD-BEARING — without it, app-shell will stub every route with \`PlaceholderScreen\` and the app boots to a black screen (observed failure mode in run-3).

**Universal wiring rules:**

1. **Auth screens** (Welcome, Login, SignUp, ForgotPassword, OAuthCallback, RoleSelect) are owned by the \`auth\` biome. Auth's HYPHA outputs MUST include these screen files; if the biome ships only contexts/hooks without screens, the audit fails.

2. **Tab screens** (Home, Inbox, Bookings, Profile, etc.) are owned by the biome that owns the tab's domain — NOT by app-shell. App-shell only owns the \`TabNavigator\` wrapper itself.

3. **Onboarding flows** are owned by their respective onboarding biome (e.g., talent-onboarding owns all \`Onboarding.Talent.*\` routes).

4. **Domain feature screens** (booking, messaging, jobs, etc.) are owned by the biome whose name matches.

**Required table format** (planner generates from §E's route map; app-shell consumes verbatim in \`RootNavigator.tsx\`):

| Route | Owner biome | Screen file path | Import statement |
|---|---|---|---|
| \`Welcome\` | auth | \`src/screens/auth/WelcomeScreen.tsx\` | \`import { WelcomeScreen } from '@/screens/auth/WelcomeScreen';\` |
| \`Auth.SignIn\` | auth | \`src/screens/auth/SignInScreen.tsx\` | \`import { SignInScreen } from '@/screens/auth/SignInScreen';\` |
| \`Tabs.Discover\` | discovery | \`src/screens/home/HomeScreen.tsx\` | \`import { HomeScreen } from '@/screens/home/HomeScreen';\` |
| ... (every route in §E gets a row here) | ... | ... | ... |

**Anti-pattern (FORBIDDEN):** \`function PlaceholderScreen() { return null; }\` and wiring all routes to it. Either ship the real screen, or ship a visible placeholder showing the route name on the theme background.

**App-shell wiring rule:** \`RootNavigator.tsx\` MUST contain exactly one \`<Stack.Screen ... component={...} />\` per route in §E, and the \`component\` value MUST be the imported real screen (not an inline stub). If the owning biome's HYPHA includes a screen as a deliverable but the file doesn't exist, the audit blocks freeze.`;

const SECURITY_RULES = `Section H is the security contract surface for the expo-supabase stack. Rules are tagged with tiers: \`[demo]\` applies starting at demo (everywhere), \`[startup]\` applies at startup and regulated, \`[regulated]\` applies only at regulated, \`[always-block]\` is the catastrophic floor that blocks at every tier and cannot be allowlisted.

Tier ordering: \`demo < startup < regulated\`. The \`organism.security_tier\` field in mycelium.yaml selects the active tier. \`mycelium contracts audit\` enforces rules at-tier-or-below plus all \`[always-block]\` rules. Per-rule allowlists with \`reason + expires\` live in mycelium.yaml under \`organism.security_allowlist\`.

#### H.1 Secret Management

##### H.1.1 No hardcoded secrets in committed code [always-block]
Rule: No real API keys, tokens, or credentials in committed source. Exempt:
  literals containing the substring \`placeholder\` (case-sensitive) matching
  the §F.7 demo-stub fallback pattern.
Audit: \`grep -rEn 'sk_live_|sk_test_|eyJ[A-Za-z0-9]{30,}|service_role|AKIA[0-9A-Z]{16}' src/ supabase/\` excluding lines containing \`placeholder\` returns zero matches.
Violation: freeze-block at all tiers. Cannot be allowlisted.

##### H.1.2 .env gitignored, .env.example committed [demo]
Rule: \`.env\` is listed in \`.gitignore\`. \`.env.example\` (with no real values, only key names) IS committed. No \`.env*\` files are tracked by git except \`.env.example\`.
Audit: parse \`.gitignore\`; require \`.env\` listed. \`git ls-files\` returns no matches for \`.env\` or \`.env.local\` etc.; may return \`.env.example\`.
Violation: demo=advisory, startup+=freeze-block.

##### H.1.3 Service-role keys never reach client code [always-block]
Rule: The literal \`service_role\` MUST NOT appear in any file under \`src/\`. Allowed in \`supabase/functions/\` (server functions) and \`supabase/migrations/\` (server-side SQL) only.
Audit: \`grep -rn 'service_role' src/\` returns zero matches.
Violation: freeze-block at all tiers. Cannot be allowlisted.

##### H.1.4 Secrets sourced from a secret manager [startup]
Rule: At startup tier, runtime secrets are sourced from a secret manager (Doppler, 1Password CLI, AWS Secrets Manager, Vault, or equivalent), not raw env vars in CI. Documented in CLAUDE.md or README.
Audit: README or CLAUDE.md contains a "Secrets" or "Secret Management" section that names a secret manager; OR a \`.doppler.yaml\` / \`.1password\` / equivalent config file exists at the cultivation root.
Violation: startup+=freeze-block. Allowlistable with documented Q-X rollout date.

##### H.1.5 Secret rotation runbook documented [regulated]
Rule: At regulated tier, a \`docs/runbooks/secret-rotation.md\` (or equivalent) exists, lists every secret in the manifest, and specifies max age per secret (90 days default).
Audit: file exists; contains a table or list mapping secret name → max age.
Violation: regulated=freeze-block.

#### H.2 Auth Flows

##### H.2.1 OAuth PKCE only — no implicit grant [demo]
Rule: All OAuth flows use the PKCE extension. No implicit-grant flows.
  expo-auth-session's \`useAuthRequest\` accepts a \`responseType: 'code'\`
  config — that is the required path. Implicit grant (\`responseType: 'token'\`)
  is forbidden.
Audit: grep \`responseType:\\s*['"]token['"]\` in src/; must return zero matches.
  Optionally, grep \`code_challenge\` to verify PKCE is wired (advisory).
Violation: demo=advisory, startup+=freeze-block.

##### H.2.2 Tokens in expo-secure-store via adapter; never raw AsyncStorage [demo, expo-supabase]
Rule: Supabase session tokens MUST be persisted via the secureStorageAdapter
  (which wraps expo-secure-store with the AsyncStorage interface, chunking
  values across keys to bypass the 2KB-per-value limit). Raw AsyncStorage
  is forbidden for any auth/session/token persistence.
Audit: in any \`createClient(...)\` call's \`auth.storage\` argument, the
  identifier MUST resolve to an expo-secure-store-backed adapter — NOT raw
  AsyncStorage. Regex approximation: grep \`storage:\\s*AsyncStorage\` in src/
  must return zero matches.

The canonical adapter is shipped by the app-shell biome at
\`src/lib/secureStorage.ts\`:

\`\`\`ts
import * as SecureStore from 'expo-secure-store';

const CHUNK_SIZE = 1800; // bytes; under expo-secure-store's 2KB limit

export const secureStorageAdapter = {
  async getItem(key: string): Promise<string | null> {
    const meta = await SecureStore.getItemAsync(\`\${key}__meta\`);
    if (!meta) return null;
    const { chunks } = JSON.parse(meta);
    const parts = await Promise.all(
      Array.from({ length: chunks }, (_, i) =>
        SecureStore.getItemAsync(\`\${key}__\${i}\`)
      )
    );
    return parts.join('');
  },
  async setItem(key: string, value: string): Promise<void> {
    const chunks = Math.ceil(value.length / CHUNK_SIZE);
    await SecureStore.setItemAsync(\`\${key}__meta\`, JSON.stringify({ chunks }));
    await Promise.all(
      Array.from({ length: chunks }, (_, i) =>
        SecureStore.setItemAsync(
          \`\${key}__\${i}\`,
          value.slice(i * CHUNK_SIZE, (i + 1) * CHUNK_SIZE)
        )
      )
    );
  },
  async removeItem(key: string): Promise<void> {
    const meta = await SecureStore.getItemAsync(\`\${key}__meta\`);
    if (!meta) return;
    const { chunks } = JSON.parse(meta);
    await Promise.all([
      SecureStore.deleteItemAsync(\`\${key}__meta\`),
      ...Array.from({ length: chunks }, (_, i) =>
        SecureStore.deleteItemAsync(\`\${key}__\${i}\`)
      ),
    ]);
  },
};
\`\`\`

Supabase client wiring (replaces §F.7's AsyncStorage example):

\`\`\`ts
import { createClient } from '@supabase/supabase-js';
import { secureStorageAdapter } from '@/lib/secureStorage';

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: secureStorageAdapter,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
});
\`\`\`
Violation: demo=advisory, startup+=freeze-block.

##### H.2.3 Session refresh with rotating tokens [startup]
Rule: \`autoRefreshToken: true\` is set on createClient. The app handles
  refresh failures by signing out cleanly (no silent stale-token reuse).
Audit: grep \`autoRefreshToken: true\` in src/lib/supabase.ts (or equivalent);
  must match.
Violation: startup+=freeze-block.

##### H.2.4 Short-lived access tokens (<1hr) [regulated]
Rule: Supabase JWT expiry configured to ≤3600 seconds. Documented in the
  cultivation's Supabase project settings checklist.
Audit: README or CLAUDE.md contains a Supabase config section noting JWT
  expiry ≤3600s.
Violation: regulated=freeze-block.

#### H.3 Database (RLS)

##### H.3.1 Every Supabase table has RLS enabled [always-block]
Rule: Every \`CREATE TABLE\` in supabase/migrations/*.sql is followed within
  the same migration file by an \`ALTER TABLE <name> ENABLE ROW LEVEL SECURITY\`.
Audit: parse migration SQL; for each \`CREATE TABLE <name>\`, verify a
  corresponding \`ALTER TABLE <name> ENABLE ROW LEVEL SECURITY\` exists in
  the same file. v1: regex-based. v2: ts-pg-parse for stricter coverage.
Violation: freeze-block at all tiers. Cannot be allowlisted.

##### H.3.2 No table grants SELECT * to anon role [demo]
Rule: No RLS policy grants unrestricted SELECT to the \`anon\` role. Policies
  TO anon must specify column-level grants OR have a USING clause that
  restricts rows.
Audit: parse migration SQL; flag any \`CREATE POLICY ... TO anon\` that
  lacks a column list AND lacks a USING clause; OR any \`GRANT SELECT ON ...
  TO anon\` without column restrictions.
Violation: demo=advisory, startup+=freeze-block.

##### H.3.3 Explicit policies per role on every table [startup]
Rule: Every table has at least one \`CREATE POLICY\` for each role in the
  organism's role set (e.g., authenticated, plus any custom roles defined
  in §C). Tables without policies (RLS enabled but no policies) are locked
  except for service_role — which violates H.1.3 if accessed from client.
Audit: parse migration SQL; for each table, count policies per role; flag
  tables with zero policies for non-service roles.
Violation: startup+=freeze-block.

##### H.3.4 service_role only in server functions [demo]
Rule: \`service_role\` key (literal or env var \`SUPABASE_SERVICE_ROLE_KEY\`)
  used only in \`supabase/functions/*\` or server-side code. Never in \`src/\`.
  This is paired with H.1.3 (which is the always-block version).
Audit: grep \`SUPABASE_SERVICE_ROLE_KEY\` in src/; must return zero.
Violation: demo=advisory (paired with H.1.3 always-block), startup+=freeze-block.

##### H.3.5 Row-level audit trail on PII tables [regulated]
Rule: Tables containing PII columns (per H.4.4 annotations) MUST have a
  trigger that logs every INSERT/UPDATE/DELETE to an audit_log table with
  user_id, timestamp, and operation type.
Audit: parse migration SQL; for each table with a PII annotation comment,
  verify a CREATE TRIGGER exists for INSERT/UPDATE/DELETE pointing at
  audit_log.
Violation: regulated=freeze-block.

#### H.4 PII Handling

##### H.4.1 PII categories defined [demo]
Rule: NUTRIENTS.md §H.4 (this section) explicitly defines what counts as
  PII for this organism. Default vocabulary (override in NUTRIENTS to add
  domain-specific items): email, phone, postal/street address, payment
  info (card number, bank account), real legal name, geolocation
  coordinates (lat/lng), national identifiers (SSN, government ID),
  date of birth, health/medical data.
Audit: this rule is contract-vs-contract — verifies the PII vocabulary is
  present in NUTRIENTS, not in source. The audit prompt checks for it.
Violation: demo=advisory, startup+=freeze-block.

##### H.4.2 No PII in console.log or analytics events [demo]
Rule: Source code MUST NOT pass PII-tagged identifiers (per H.4.1
  vocabulary) into \`console.log\`, \`console.warn\`, \`console.error\`,
  \`console.info\`, \`analytics.track()\`, \`Sentry.captureException()\`, or
  any equivalent telemetry sink. Use sanitized references instead
  (user_id, not email; "card ending in X", not full PAN).
Audit: regex grep on src/: \`console\\.(log|warn|error|info)\\([^)]*\\b(email|phone|address|ssn|password|token|api[_-]?key)\\b\` — flag matches. v1: identifier-name match (approximate). v2: TS AST tracking variable types tagged @pii.
Violation: demo=advisory, startup+=freeze-block.

##### H.4.3 Error messages sanitize PII; user IDs only [startup]
Rule: User-facing error messages display user_id, never email or phone.
  Backend error responses returned to clients are sanitized (no stack
  traces, no DB error text containing PII fields).
Audit: regex grep for error-handling patterns that include PII identifiers
  in toast/alert/error-throw arguments. v1: heuristic. v2: TS AST.
Violation: startup+=freeze-block.

##### H.4.4 PII columns annotated for audit detection [startup]
Rule: Every column in supabase/migrations/*.sql holding a PII value carries
  a SQL comment with the literal token \`@pii\`, optionally followed by the
  category. Example:
  \`\`\`sql
  CREATE TABLE profiles (
    id uuid PRIMARY KEY,
    email text NOT NULL,  -- @pii email
    phone text,           -- @pii phone
    legal_name text       -- @pii name
  );
  \`\`\`
  This makes PII columns programmatically detectable for H.3.5 (audit
  trail), H.4.5 (access logging), and downstream tooling.
Audit: parse migration SQL; for known-PII column name patterns (email,
  phone, address, ssn, name, dob, etc.), verify an adjacent \`-- @pii\`
  comment exists. v1: regex. v2: SQL parser.
Violation: startup+=freeze-block.

##### H.4.5 PII access logged with role + reason [regulated]
Rule: Backend code reading PII columns from PII-annotated tables (per
  H.4.4) emits an access-log entry with: requesting user_id, role, target
  user_id, columns accessed, reason code. Documented logging
  infrastructure required.
Audit: README or CLAUDE.md contains a "PII Access Logging" section
  describing the audit-log schema and write path.
Violation: regulated=freeze-block.
`;

export const EXPO_SUPABASE_APPENDIX: ContractAppendix = {
  preamble: PREAMBLE,
  dependencyManifest: DEPENDENCY_MANIFEST,
  primitiveProps: PRIMITIVE_PROPS,
  baselineOwnership: BASELINE_OWNERSHIP,
  barrelOwnership: BARREL_OWNERSHIP,
  allowlistedIdentifiers: ALLOWLISTED_IDENTIFIERS,
  styleSystemRules: STYLE_SYSTEM_RULES,
  screenOwnershipMatrix: SCREEN_OWNERSHIP_MATRIX,
  securityRules: SECURITY_RULES,
};
